# Generated by Django 3.0.8 on 2020-07-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feedbacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='comment',
            new_name='commen',
        ),
        migrations.RenameField(
            model_name='feedbacks',
            old_name='post',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='feedbacks',
            old_name='name',
            new_name='posts',
        ),
    ]
